INSERT INTO courses (code, name, faculty) VALUES
    ('CS1026', 'Computer Science Fundamentals I', 'Science'),
    ('CS1027', 'Computer Science Fundamentals II', 'Science'),
    ('CS2210', 'Data Structures and Algorithms', 'Science'),
    ('CS2211', 'Software Tools and Systems Programming', 'Science'),
    ('CS2212', 'Introduction to Software Engineering', 'Science'),
    ('CS3305', 'Operating Systems', 'Science'),
    ('CS3340', 'Analysis of Algorithms', 'Science'),
    ('MATH1228', 'Methods of Finite Mathematics', 'Science'),
    ('MATH1229', 'Methods of Matrix Algebra', 'Science'),
    ('MATH1600', 'Linear Algebra I', 'Science'),
    ('ECON1021', 'Principles of Microeconomics', 'Social Science'),
    ('ECON1022', 'Principles of Macroeconomics', 'Social Science'),
    ('PSYCH1000', 'Introduction to Psychology', 'Social Science'),
    ('BUS1220', 'Introduction to Financial Accounting', 'Business'),
    ('BUS2257', 'Organizational Behaviour', 'Business'),
    ('MOS2275', 'Business Statistics', 'Social Science'),
    ('CHEM1301', 'Discovering Chemical Structure', 'Science'),
    ('BIOLOGY1001', 'Biology for Science I', 'Science'),
    ('ENG1020', 'Understanding Literature Today', 'Arts and Humanities'),
    ('PHIL1020', 'Introduction to Philosophy', 'Arts and Humanities');
